---
- name: Check and Report Disk Usage on Servers
  hosts: all
  become: true

  tasks:
    - name: Check disk usage
      command: df -h
      register: disk_usage_raw

    - name: Parse disk usage
      set_fact:
        disk_usage: >
          {{
            disk_usage_raw.stdout_lines[1:] | 
            map('regex_replace', '\s+', ' ') |
            map('split', ' ') | 
            map('join', ' | ') | 
            join('\n')
          }}

    - name: Display disk usage in structured format
      debug:
        msg: |
          Disk Usage Report for {{ inventory_hostname }}:
          Filesystem | Size | Used | Available | Use% | Mounted on
          --------------------------------------------------------
          {{ disk_usage }}
