---
- hosts: all
  become: true

  tasks:
    - name: Pull Jenkins Docker image
      docker_image:
        name: jenkins/jenkins
        tag: lts-jdk17
        source: pull

    - name: Run Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk17
        state: started
        restart_policy: on-failure
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
