apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    app: web-server
    environment: production
  annotations:
    description: "This pod runs the web server for production environment"
spec:
  containers:
  - name: web-server
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    env:
    - name: ENVIRONMENT
      value: "production"
    - name: LOG_LEVEL
      value: "info"
    readinessProbe:
      httpGet:
        path: /  # Changed to root path
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /  # Changed to root path
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
    volumeMounts:
    - name: web-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-data
    emptyDir: {}
  restartPolicy: Always
