apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  type: NodePort  # Exposes the service externally using a NodePort
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80  # Service port (inside the cluster)
    targetPort: 80  # Target port (inside the container)
    nodePort: 31848  # External port to access the service from outside the cluster (within the valid range)
